# Generated by Django 2.1.5 on 2019-01-24 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='歌名', max_length=30, verbose_name='歌曲名称')),
                ('singer', models.CharField(default='未知歌手', help_text='歌手', max_length=20, verbose_name='歌手名')),
                ('album', models.CharField(default='未知专辑', help_text='专辑', max_length=20, verbose_name='专辑名')),
                ('music', models.FileField(help_text='文件', upload_to='musics/musics', verbose_name='歌曲文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='喜欢数')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
    ]
