# Generated by Django 2.1.5 on 2019-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyric',
            field=models.FileField(blank=True, help_text='歌词', null=True, upload_to='musics/lyric', verbose_name='歌词'),
        ),
    ]
