# Generated by Django 2.1.5 on 2019-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20190124_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='musics/images', verbose_name='图片'),
        ),
    ]
